export const API_URL = "http://localhost:8000/api/"
export const ADD_EXPENSE = 'ADD_EXPENSE'; 
export const UPDATE_EXPENSE = 'UPDATE_EXPENSE';
export const DELETE_EXPENSE = 'DELETE_EXPENSE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const COUNT_CLICK = 'COUNT_CLICK';

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const FETCH_API_EXPENSES = "FETCH_API_EXPENSES";
export const DELETE_API_EXPENSE = "DELETE_API_EXPENSE";
export const FETCH_API_EXPENSES_REQUEST = 'FETCH_API_EXPENSES_REQUEST';
export const FETCH_API_EXPENSES_FAILURE = 'FETCH_API_EXPENSES_FAILURE';

export const DELETE_API_EXPENSES_REQUEST = 'DELETE_API_EXPENSES_REQUEST';
export const DELETE_API_EXPENSES_FAILURE = 'DELETE_API_EXPENSES_FAILURE';

export const ADD_API_EXPENSES_REQUEST = 'ADD_API_EXPENSES_REQUEST';
export const ADD_API_EXPENSE = "ADD_API_EXPENSE";

export const UPDATE_API_EXPENSES_REQUEST = "UPDATE_API_EXPENSES_REQUEST";
export const UPDATE_API_EXPENSES_RECORD = "UPDATE_API_EXPENSES_RECORD";
